### ISSUE TITLE
element() return invisible elements.

### ISSUE THREAD

**Issue by EreOo** [WileyLabs/teasy#21]
Method element() return elements with css visibility:hidden. It's not good, because method must return elements with displayed = true.

![screen shot 2017-07-20 at 15 22 50](https://user-images.githubusercontent.com/18676678/28418316-e86f0822-6d63-11e7-94d7-1b9db0d3c2fe.png)

**Comment by vefimofff** [comment]
Good catch @EreOo. It's a bit inaccurate to say that it should only return with isDisplayed = true, because the idea is that it should return elements that user can interact with. But I get your point. Could you please improve isElementHiddenUnderScroll methid in ExpectedCondition2 to make it take "visibility:hidden" into consideration as well.
